#!/usr/bin/env node
/**
 * SCOREBUG // SHIELD MIRROR
 *
 *   node scripts/gen-shields.mjs [path-to-scorebug-app]
 *
 * Reads the app's Broadcast Shield dictionaries (lib/data/nhl.ts, nfl.ts,
 * mlb.ts, badges.gen.ts and the hand-seeded supplement + aliases in
 * badges.ts) and writes app/lib/shields.gen.ts — the compact form the card
 * press needs. Run it whenever the app adds a club. The app's files are the
 * source of truth; this file never edits them.
 *
 * Parsed with regular expressions rather than a TypeScript compiler on
 * purpose: the entries are one object literal per line with five fixed keys,
 * and pulling in a compiler for that would be the heavier dependency.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE = resolve(HERE, '..');
const APP = resolve(process.argv[2] || join(SITE, '..', 'scorebug-app'));
const DATA = join(APP, 'lib', 'data');

const ENTRY = /\{\s*(?:id:\s*'[^']*',\s*)?abbr:\s*'([^']+)',\s*name:\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"),\s*primaryColor:\s*'([^']+)',\s*secondaryColor:\s*'([^']+)',\s*accentColor:\s*'([^']+)',\s*geometryType:\s*'([^']+)'\s*\}/g;

function block(src, startPattern) {
  const m = startPattern.exec(src);
  if (!m) return '';
  let i = m.index + m[0].length, depth = 1;
  while (depth && i < src.length) { if (src[i] === '[') depth += 1; else if (src[i] === ']') depth -= 1; i += 1; }
  return src.slice(m.index + m[0].length, i);
}
function entries(text) {
  const out = [];
  for (const e of text.matchAll(ENTRY)) {
    const [, abbr, n1, n2, p, s, a, g] = e;
    out.push([abbr.toUpperCase(), (n1 ?? n2).replace(/\\'/g, "'").replace(/\\"/g, '"'), p, s, a, g]);
  }
  return out;
}

const gen = await readFile(join(DATA, 'badges.gen.ts'), 'utf8');
const leagues = {};
for (const id of ['NBA', 'NCAAF', 'NCAAB', 'EPL', 'LALIGA', 'SERIEA', 'BUND', 'LIGUE1', 'UCL', 'MLS', 'CFL', 'CSL', 'ISL', 'JLEAGUE', 'IPL']) {
  leagues[id] = entries(block(gen, new RegExp(`export const ${id}_BADGES: BadgeTeam\\[\\] = \\[`)));
}
leagues.NHL = entries(block(await readFile(join(DATA, 'nhl.ts'), 'utf8'), /export const NHL_TEAMS: NhlTeam\[\] = \[/));
leagues.NFL = entries(block(await readFile(join(DATA, 'nfl.ts'), 'utf8'), /export const NFL_TEAMS: BadgeTeam\[\] = \[/));
leagues.MLB = entries(block(await readFile(join(DATA, 'mlb.ts'), 'utf8'), /export const MLB_TEAMS: BadgeTeam\[\] = \[/));

const badges = await readFile(join(DATA, 'badges.ts'), 'utf8');
const sup = badges.slice(badges.indexOf('const SUPPLEMENTAL'), badges.indexOf('function build('));
for (const m of sup.matchAll(/^\s*([A-Z0-9]+):\s*\[/gm)) {
  const lg = m[1];
  const text = block(sup.slice(m.index), /\[/);
  const have = new Set((leagues[lg] || []).map((r) => r[0]));
  for (const row of entries(text)) if (!have.has(row[0])) (leagues[lg] ||= []).push(row);
}
const aliases = {};
const dicts = badges.slice(badges.indexOf('const DICTS'), badges.indexOf('const SOCCER_FALLBACKS'));
for (const m of dicts.matchAll(/^\s*([A-Z0-9]+):\s*build\([A-Z_]+,\s*\{([^}]*)\}/gm)) {
  const d = {};
  for (const p of m[2].matchAll(/([A-Z0-9&'"-]+|'[^']+'):\s*'([^']+)'/g)) d[p[1].replace(/^'|'$/g, '').toUpperCase()] = p[2].toUpperCase();
  if (Object.keys(d).length) aliases[m[1]] = d;
}

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const lines = [
  '// AUTO-GENERATED by scorebug-site/scripts/gen-shields.mjs from scorebug-app/lib/data — do not edit by hand.',
  '// The app\'s Broadcast Shield dictionaries, compacted for the card press: [primary, secondary, accent, geometry, name].',
  '// Original, legally-distinct crests drawn from each club\'s published colours; no trademarked logo is ever used.',
  "export type Geometry = 'triple-band' | 'solid-band' | 'chevron' | 'diagonal' | 'yoke'",
  'export type ShieldRow = readonly [string, string, string, Geometry, string]',
  'export const SHIELDS: Record<string, Record<string, ShieldRow>> = {',
];
for (const lg of ['NHL', 'NFL', 'NBA', 'MLB', 'CFL', 'NCAAF', 'NCAAB', 'EPL', 'UCL', 'LALIGA', 'SERIEA', 'BUND', 'LIGUE1', 'MLS', 'CSL', 'ISL', 'JLEAGUE', 'IPL']) {
  lines.push(`  ${lg}: {`);
  for (const [abbr, name, p, s, a, g] of leagues[lg] || []) lines.push(`    ${q(abbr)}: [${q(p)}, ${q(s)}, ${q(a)}, ${q(g)}, ${q(name)}],`);
  lines.push('  },');
}
lines.push('}');
lines.push(`export const ALIASES: Record<string, Record<string, string>> = ${JSON.stringify(aliases).replace(/"/g, "'")}`);
lines.push("export const SOCCER_FALLBACKS: Record<string, string[]> = { UCL: ['EPL', 'LALIGA', 'SERIEA', 'BUND', 'LIGUE1'], EPL: ['UCL'], LALIGA: ['UCL'], SERIEA: ['UCL'], BUND: ['UCL'], LIGUE1: ['UCL'] }");
await writeFile(join(SITE, 'app', 'lib', 'shields.gen.ts'), `${lines.join('\n')}\n`, 'utf8');
const total = Object.values(leagues).reduce((s, v) => s + v.length, 0);
console.log(`wrote app/lib/shields.gen.ts — ${total} shields across ${Object.keys(leagues).length} leagues`);
